export const TEAMS_2026 = [
  // CONMEBOL
  { name: 'Argentina', code: 'ARG', confederation: 'CONMEBOL', flagUrl: '🇦🇷' },
  { name: 'Brasil', code: 'BRA', confederation: 'CONMEBOL', flagUrl: '🇧🇷' },
  { name: 'Uruguay', code: 'URU', confederation: 'CONMEBOL', flagUrl: '🇺🇾' },
  { name: 'Colombia', code: 'COL', confederation: 'CONMEBOL', flagUrl: '🇨🇴' },
  { name: 'Ecuador', code: 'ECU', confederation: 'CONMEBOL', flagUrl: '🇪🇨' },
  { name: 'Perú', code: 'PER', confederation: 'CONMEBOL', flagUrl: '🇵🇪' },
  { name: 'Chile', code: 'CHI', confederation: 'CONMEBOL', flagUrl: '🇨🇱' },
  { name: 'Paraguay', code: 'PAR', confederation: 'CONMEBOL', flagUrl: '🇵🇾' },
  { name: 'Venezuela', code: 'VEN', confederation: 'CONMEBOL', flagUrl: '🇻🇪' },
  { name: 'Bolivia', code: 'BOL', confederation: 'CONMEBOL', flagUrl: '🇧🇴' },
  // UEFA
  { name: 'España', code: 'ESP', confederation: 'UEFA', flagUrl: '🇪🇸' },
  { name: 'Francia', code: 'FRA', confederation: 'UEFA', flagUrl: '🇫🇷' },
  { name: 'Alemania', code: 'GER', confederation: 'UEFA', flagUrl: '🇩🇪' },
  { name: 'Inglaterra', code: 'ENG', confederation: 'UEFA', flagUrl: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  { name: 'Italia', code: 'ITA', confederation: 'UEFA', flagUrl: '🇮🇹' },
  { name: 'Países Bajos', code: 'NED', confederation: 'UEFA', flagUrl: '🇳🇱' },
  { name: 'Portugal', code: 'POR', confederation: 'UEFA', flagUrl: '🇵🇹' },
  { name: 'Bélgica', code: 'BEL', confederation: 'UEFA', flagUrl: '🇧🇪' },
  { name: 'Croacia', code: 'CRO', confederation: 'UEFA', flagUrl: '🇭🇷' },
  { name: 'Dinamarca', code: 'DEN', confederation: 'UEFA', flagUrl: '🇩🇰' },
  { name: 'Suiza', code: 'SUI', confederation: 'UEFA', flagUrl: '🇨🇭' },
  { name: 'Serbia', code: 'SRB', confederation: 'UEFA', flagUrl: '🇷🇸' },
  // CONCACAF
  { name: 'México', code: 'MEX', confederation: 'CONCACAF', flagUrl: '🇲🇽' },
  { name: 'Estados Unidos', code: 'USA', confederation: 'CONCACAF', flagUrl: '🇺🇸' },
  { name: 'Canadá', code: 'CAN', confederation: 'CONCACAF', flagUrl: '🇨🇦' },
  { name: 'Costa Rica', code: 'CRC', confederation: 'CONCACAF', flagUrl: '🇨🇷' },
  { name: 'Panamá', code: 'PAN', confederation: 'CONCACAF', flagUrl: '🇵🇦' },
  { name: 'Jamaica', code: 'JAM', confederation: 'CONCACAF', flagUrl: '🇯🇲' },
  // CAF
  { name: 'Marruecos', code: 'MAR', confederation: 'CAF', flagUrl: '🇲🇦' },
  { name: 'Senegal', code: 'SEN', confederation: 'CAF', flagUrl: '🇸🇳' },
  { name: 'Nigeria', code: 'NGA', confederation: 'CAF', flagUrl: '🇳🇬' },
  { name: 'Camerún', code: 'CMR', confederation: 'CAF', flagUrl: '🇨🇲' },
  { name: 'Ghana', code: 'GHA', confederation: 'CAF', flagUrl: '🇬🇭' },
  { name: 'Costa de Marfil', code: 'CIV', confederation: 'CAF', flagUrl: '🇨🇮' },
  { name: 'Egipto', code: 'EGY', confederation: 'CAF', flagUrl: '🇪🇬' },
  { name: 'Túnez', code: 'TUN', confederation: 'CAF', flagUrl: '🇹🇳' },
  { name: 'Argelia', code: 'ALG', confederation: 'CAF', flagUrl: '🇩🇿' },
  // AFC
  { name: 'Japón', code: 'JPN', confederation: 'AFC', flagUrl: '🇯🇵' },
  { name: 'Corea del Sur', code: 'KOR', confederation: 'AFC', flagUrl: '🇰🇷' },
  { name: 'Arabia Saudita', code: 'KSA', confederation: 'AFC', flagUrl: '🇸🇦' },
  { name: 'Australia', code: 'AUS', confederation: 'AFC', flagUrl: '🇦🇺' },
  { name: 'Irán', code: 'IRN', confederation: 'AFC', flagUrl: '🇮🇷' },
  { name: 'Irak', code: 'IRQ', confederation: 'AFC', flagUrl: '🇮🇶' },
  { name: 'Catar', code: 'QAT', confederation: 'AFC', flagUrl: '🇶🇦' },
  { name: 'Emiratos Árabes', code: 'UAE', confederation: 'AFC', flagUrl: '🇦🇪' },
  // OFC
  { name: 'Nueva Zelanda', code: 'NZL', confederation: 'OFC', flagUrl: '🇳🇿' },
  { name: 'Tahití', code: 'TAH', confederation: 'OFC', flagUrl: '🇵🇫' },
];
